server {
  # on définit le port où NGINX écoute dans le conteneur
  listen 80;
  
  # on définit le chemin vers la racine web
  # dans ce dossier doit se trouver un fichier index.html
  root /var/www/tp_docker; 
}
